version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - New_SECRET_KEY=bk_j@niw96)h$dga_!44=^9+7d53q(c7hz)7mgm&j!a(+&hqb4
      - databasepassword=adebimpe1994
    volumes:
      - .:/code
    ports:
      - 8000:8000




  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: midecreative
      POSTGRES_PASSWORD: adebimpe1994
      POSTGRES_DB: ecommerce_db

volumes:
  postgres_data:
