# Generated by Django 2.2 on 2021-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='drink_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='drink_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='drink',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='this item should come with a description'),
        ),
    ]
