# Generated by Django 2.2 on 2021-12-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211230_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='drinks',
            new_name='items',
        ),
    ]
